FROM nginx:1.24

LABEL org.opencontainers.image.source=https://github.com/keyruu/traversetown
LABEL org.opencontainers.image.description="Frontend for traversetown"
LABEL org.opencontainers.image.licenses=AGPL-3.0-only

COPY build /etc/nginx/html

EXPOSE 80