apiVersion: v1
kind: ServiceAccount
metadata:
  name: apifix
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: apifix
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apifix
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: apifix
subjects:
  - kind: ServiceAccount
    name: apifix
