name: Build and Push Frontend

on:
  push:
    paths:
      - frontend/**
    branches:
      - main
  workflow_dispatch:

jobs:
  frontend:
    runs-on: [ubuntu-latest]
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Docker build and push
        uses: docker/build-push-action@v3
        with:
          context: astro-frontend/
          file: astro-frontend/docker/image/Dockerfile
          push: true
          tags: ghcr.io/keyruu/traversetown/frontend:latest